export default {
  API_CALL: 'API_CALL',

  LOCATION_CHANGED: '@@router/LOCATION_CHANGE',
  CLEAR_USER_STORE_DATA: 'CLEAR_USER_STORE_DATA',

  ADD_TUTORIAL_REQUEST: 'ADD_TUTORIAL_REQUEST',
  ADD_TUTORIAL_SUCCESS: 'ADD_TUTORIAL_SUCCESS',
  ADD_TUTORIAL_FAILURE: 'ADD_TUTORIAL_FAILURE',

  GET_TUTORIALS_REQUEST: 'GET_TUTORIALS_REQUEST',
  GET_TUTORIALS_SUCCESS: 'GET_TUTORIALS_SUCCESS',
  GET_TUTORIALS_FAILURE: 'GET_TUTORIALS_FAILURE',

  UPDATE_TUTORIAL_REQUEST: 'UPDATE_TUTORIAL_REQUEST',
  UPDATE_TUTORIAL_SUCCESS: 'UPDATE_TUTORIAL_SUCCESS',
  UPDATE_TUTORIAL_FAILURE: 'UPDATE_TUTORIAL_FAILURE',

  DELETE_TUTORIAL_REQUEST: 'DELETE_TUTORIAL_REQUEST',
  DELETE_TUTORIAL_SUCCESS: 'DELETE_TUTORIAL_SUCCESS',
  DELETE_TUTORIAL_FAILURE: 'DELETE_TUTORIAL_FAILURE',

  DELETE_ALL_TUTORIALS_REQUEST: 'DELETE_ALL_TUTORIALS_REQUEST',
  DELETE_ALL_TUTORIALS_SUCCESS: 'DELETE_ALL_TUTORIALS_SUCCESS',
  DELETE_ALL_TUTORIALS_FAILURE: 'DELETE_ALL_TUTORIALS_FAILURE',

  CLEAR_TUTORIAL_SUBMITTED_STATE: 'CLEAR_TUTORIAL_SUBMITTED_STATE',
};
