export default {
  API_CALL: 'API_CALL',

  LOCATION_CHANGED: '@@router/LOCATION_CHANGE',
  CLEAR_USER_STORE_DATA: 'CLEAR_USER_STORE_DATA',

  ADD_TUTORIAL_REQUEST: 'ADD_TUTORIAL_REQUEST',
  ADD_TUTORIAL_SUCCESS: 'ADD_TUTORIAL_SUCCESS',
  ADD_TUTORIAL_FAILURE: 'ADD_TUTORIAL_FAILURE',

  GET_TUTORIALS_REQUEST: 'GET_TUTORIALS_REQUEST',
  GET_TUTORIALS_SUCCESS: 'GET_TUTORIALS_SUCCESS',
  GET_TUTORIALS_FAILURE: 'GET_TUTORIALS_FAILURE',

  UPDATE_TUTORIAL_REQUEST: 'UPDATE_TUTORIAL_REQUEST',
  UPDATE_TUTORIAL_SUCCESS: 'UPDATE_TUTORIAL_SUCCESS',
  UPDATE_TUTORIAL_FAILURE: 'UPDATE_TUTORIAL_FAILURE',

  DELETE_TUTORIAL_REQUEST: 'DELETE_TUTORIAL_REQUEST',
  DELETE_TUTORIAL_SUCCESS: 'DELETE_TUTORIAL_SUCCESS',
  DELETE_TUTORIAL_FAILURE: 'DELETE_TUTORIAL_FAILURE',

  DELETE_ALL_TUTORIALS_REQUEST: 'DELETE_ALL_TUTORIALS_REQUEST',
  DELETE_ALL_TUTORIALS_SUCCESS: 'DELETE_ALL_TUTORIALS_SUCCESS',
  DELETE_ALL_TUTORIALS_FAILURE: 'DELETE_ALL_TUTORIALS_FAILURE',

  CLEAR_TUTORIAL_SUBMITTED_STATE: 'CLEAR_TUTORIAL_SUBMITTED_STATE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  AUTHENTICATE_USER_REQUEST: 'AUTHENTICATE_USER_REQUEST',
  AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
  AUTHENTICATE_USER_FAILURE: 'AUTHENTICATE_USER_FAILURE',

  GET_REPORTS_REQUEST: 'GET_REPORTS_REQUEST',
  GET_REPORTS_SUCCESS: 'GET_REPORTS_SUCCESS',
  GET_REPORTS_FAILURE: 'GET_REPORTS_FAILURE',

  GET_VOLUNTEERS_REQUEST: 'GET_VOLUNTEERS_REQUEST',
  GET_VOLUNTEERS_SUCCESS: 'GET_VOLUNTEERS_SUCCESS',
  GET_VOLUNTEERS_FAILURE: 'GET_VOLUNTEERS_FAILURE',

  GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

  PATCH_REPORT_REQUEST: 'PATCH_REPORTS_REQUEST',
  PATCH_REPORT_SUCCESS: 'PATCH_REPORTS_SUCCESS',
  PATCH_REPORT_FAILURE: 'PATCH_REPORTS_FAILURE',
};
